### ISSUE TITLE
ReferenceError when running .smoke with variables

### ISSUE THREAD

**Issue by oosidat** [namshi/shisha#31]
My `.smoke` file looks like this:

```
http://{{domain1}}/{{path}}/ 200
```

(also tried a variant with spaces - like `{{ domain1 }}`)

Tried to to run shisha: 
```
$ shisha --domain1 example.org --path api
```

Got this error:

```
lodash.templateSources[0]:9
((__t = (domain1)) == null ? '' : __t) +
         ^
ReferenceError: domain1 is not defined
    at eval (lodash.templateSources[0]:9:10)
    at String.replace (native)
    at /Users/osidat/Development/test/shisha/bin/shisha.js:34:18
    at Array.forEach (native)
    at /Users/osidat/Development/test/shisha/bin/shisha.js:26:16
    at ClientRequest.<anonymous> (/Users/osidat/Development/test/shisha/src/index.js:51:21)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:426:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
```

Am I doing something wrong here?

**Comment by oosidat** [comment]
I was able to use the following patch to get rid of this problem (I changed url to be a string instead of a function):

```
From c8b8d69415253a1450a4bc645a772e2ed424fd4f Mon Sep 17 00:00:00 2001
From: Osama Sidat <osama.sidat@d2l.com>
Date: Mon, 6 Jul 2015 16:30:28 -0400
Subject: [PATCH] Changed the render function in template.js to return a string
 instead of a function.

Updated one instance in src/index.js where url was being treated as a function instead of a string.
---
 src/index.js      | 8 ++++----
 src/templating.js | 5 +++--
 2 files changed, 7 insertions(+), 6 deletions(-)

diff --git a/src/index.js b/src/index.js
index dea1eca..6340d08 100644
--- a/src/index.js
+++ b/src/index.js
@@ -52,9 +52,9 @@ var shisha = {
                 }
             };
         };
-        
+
         var testResource = function (resource) {
-            var requestOptions = url.parse(resource.url(locals));
+            var requestOptions = url.parse(resource.url);
             requestOptions.agent = false;
 
             if (options && options.caPath) {
@@ -63,7 +63,7 @@ var shisha = {
 
             http.request(requestOptions, addToReport(resource.url, resource.status)).end();
         };
-        
+
         for (var i = 0; i < resources.length; i++) {
           testResource({
             url: resources[i].url,
@@ -73,4 +73,4 @@ var shisha = {
     }
 };
 
-module.exports = shisha;
\ No newline at end of file
+module.exports = shisha;
diff --git a/src/templating.js b/src/templating.js
index ab80e34..a63afb2 100644
--- a/src/templating.js
+++ b/src/templating.js
@@ -13,7 +13,8 @@ module.exports = (function(){
 
     return {
         render: function(content, locals){
-            return engine.template(content, locals);
+            var compiledTemplate = engine.template(content);
+            return compiledTemplate(locals);
         }
     };
-})();
\ No newline at end of file
+})();
-- 
2.2.1
```

**Comment by oosidat** [comment]
Pull request submitted: https://github.com/namshi/shisha/pull/32

Changing the return value of  templating's `render` function to string instead of function fixed this problem.
